version: '3.8'

services:
  # The pipeline
  pipeline:
    build: .
    container_name: detector-pipeline
    command: tail -f /dev/null
    volumes:
      - .:/app
      - ./shared_data:/app/shared_data

  # The simulation tool
  generator:
    build: .
    container_name: detector-generator
    command: tail -f /dev/null
    volumes:
      - .:/app
      - ./shared_data:/app/shared_data